### ISSUE TITLE
nested array

### ISSUE THREAD

**Issue by kodeine** [pleerock/class-transformer#5]
Hello, i am very happy to use this library. I have a question, how would i use this if i have an array like this. Is this the correct way?

```ts
export class ManagerCollection extends Array<User> {}

    @ArrayType(() => ManagerCollection)
    public managers: {
        owners:User[],
        admins:User[],
    }
```

**Comment by pleerock** [comment]
yes you need to use @ArrayType as in example [here](https://github.com/pleerock/constructor-utils/tree/master/sample/sample3-custom-arrays). But what I see from the code, that your **managers** type is not correct, it should be `ManagerCollection` instead of  `
managers: {
        owners:User[],
        admins:User[],
    }
`

**Comment by kodeine** [comment]
@pleerock so it should be,
```ts
export class ManagerCollection extends Array<User> {
        owners:User[];
        admins:User[];
}

    @ArrayType(() => ManagerCollection)
    public managers;
```
Please correct the code if im wrong. thanks

**Comment by pleerock** [comment]
The most correct is:

```typescript
export class ManagerCollection extends Array<User> {
        owners:User[];
        admins:User[];
}

@ArrayType(() => ManagerCollection)
public managers: ManagerCollection;
```

**Comment by kodeine** [comment]
@pleerock thank you

**Comment by kodeine** [comment]
@pleerock i am still having an issue, its not transforming `mangers` as `User`.
This is how the json looks. can you please guide, thanks

```json
"managers": {
                "owners": [
                    {
                        "id": 1,
                        "username": "root",
                        "first_name": "root",
                        "last_name": "account",
                        "updated_at": "2016-05-27T00:58:09.093449Z",
                        "created_at": "2016-05-27T00:58:09.093477Z",
                        "last_login": "2016-07-03T15:45:30.574305Z",
                        "profile": null,
                        "address": null
                    }
                ],
                "admins": [
                    {
                        "id": 2,
                        "username": "test",
                        "first_name": "test",
                        "last_name": "account",
                        "updated_at": "2016-05-27T01:03:25.616857Z",
                        "created_at": "2016-05-27T01:03:25.616895Z",
                        "last_login": null,
                        "profile": null,
                        "address": null
                    }
                ]
            },
```

**Comment by pleerock** [comment]
looks like we completely forgot to specify types:

```typescript
export class ManagerCollection extends Array<User> {
        @Type(() => User)
        owners:User[];

        @Type(() => User)
        admins:User[];
}
```

**Comment by kodeine** [comment]
@pleerock ahh totally forgot about that but now works like a charm, thanks a lot :)

**Comment by pleerock** [comment]
yeah, don't forget to star projects you like ;)

**Comment by kodeine** [comment]
@pleerock 
so coming back to this problem again,  i am using 
```ts
export class ManagerCollection extends Array<User> {
        @Type(() => User)
        owners:User[];

        @Type(() => User)
        admins:User[];
}
```

and my api data is 

```json
"managers": {
                "owners": [
                    {
                        "id": 1,
                        "username": "root",
                        "first_name": "root",
                        "last_name": "account",
                        "updated_at": "2016-05-27T00:58:09.093449Z",
                        "created_at": "2016-05-27T00:58:09.093477Z",
                        "last_login": "2016-07-03T15:45:30.574305Z",
                        "profile": null,
                        "address": null
                    }
                ],
                "admins": [
                    {
                        "id": 2,
                        "username": "test",
                        "first_name": "test",
                        "last_name": "account",
                        "updated_at": "2016-05-27T01:03:25.616857Z",
                        "created_at": "2016-05-27T01:03:25.616895Z",
                        "last_login": null,
                        "profile": null,
                        "address": null
                    }
                ]
            },
```

But it's not properly transforming... this is what it transforms to.

![screenshot from 2016-10-17 13-11-44](https://cloud.githubusercontent.com/assets/8620059/19449454/475d29ae-946b-11e6-8c8d-e3104cb2f9b1.png)

Notice owner and admin are shown as User object but the nested ones are simple objects.
In fact nested should be User objects.

Can you please guide whats going on here?

Thanks

**Comment by kodeine** [comment]
nevermind, it was a problem at my end.

**Comment by msconcept** [comment]
@kodeine  what was your problem, I have the same

**Comment by fabianoalmeida** [comment]
I'm facing the same problem here.
```typescript
// cycle.create.dto.js

import { 
  IsOptional, 
  IsString, 
  IsBoolean, 
  IsArray, 
  ArrayMinSize, 
  ValidateNested 
} from 'class-validator';
import { Type } from 'class-transformer';
import { CreateWorkoutDto } from '../workouts/create.dto';

class CreateCycleDto {
  // ...

  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => CreateWorkoutDto)
  workouts: CreateWorkoutDto[];

  // ...
}
```
```typescript
// workout.create.dto.js

import { IsOptional, IsString, IsArray, ArrayMinSize, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';
import CreateExerciseDto from '../exercises/create.dto';
import IWorkout from '../../models/interfaces/workout';

export class CreateWorkoutDto extends Array<IWorkout> {
  // ...

  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => CreateExerciseDto)
  public exercises: CreateExerciseDto[];

  // ...
}
```
Error:
```sh
TypeError: Reflect.getMetadata is not a function
    at C:\Users\fabiano.almeida\projects\fabiano-io\fit-app\api\src\decorators.ts:27:39
    at __decorate (C:\Users\fabiano.almeida\projects\fabiano-io\fit-app\api\src\dto\workouts\create.dto.ts:5:110)
    at Object.<anonymous> (C:\Users\fabiano.almeida\projects\fabiano-io\fit-app\api\src\dto\workouts\create.dto.ts:18:3)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Module._compile (C:\Users\fabiano.almeida\projects\fabiano-io\fit-app\api\node_modules\source-map-support\source-map-support.js:547:25)
    at Module.m._compile (C:\Users\FABIAN~1.ALM\AppData\Local\Temp\ts-node-dev-hook-6415792758947756.js:57:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at require.extensions.<computed> (C:\Users\FABIAN~1.ALM\AppData\Local\Temp\ts-node-dev-hook-6415792758947756.js:59:14)
    at Object.nodeDevHook [as .ts] (C:\Users\fabiano.almeida\projects\fabiano-io\fit-app\api\node_modules\ts-node-dev\lib\hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\Users\fabiano.almeida\projects\fabiano-io\fit-app\api\src\dto\cycles\create.dto.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Module._compile (C:\Users\fabiano.almeida\projects\fabiano-io\fit-app\api\node_modules\source-map-support\source-map-support.js:547:25)
[ERROR] 18:38:13 TypeError: Reflect.getMetadata is not a function
```
Can you help me @kodeine?
